import React, { ReactElement } from "react";
import { Bar } from "react-chartjs-2";

export default function main(): ReactElement {
  const data = {
    labels: [
      "00:00",
      "01:00",
      "02:00",
      "03:00",
      "04:00",
      "05:00",
      "06:00",
      "07:00",
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
      "24:00",
    ],
    datasets: [
      {
        label: "Zone 1",
        data: [
          1,
          2,
          2,
          2,
          2,
          1,
          1,
          1,
          0,
          71,
          145,
          131,
          96,
          120,
          110,
          80,
          45,
          40,
          20,
          80,
          90,
          80,
          50,
          20,
          4,
        ],
        backgroundColor: "#ff808a",
      },
      {
        label: "Zone 2",
        data: [
          13,
          3,
          3,
          3,
          2,
          3,
          3,
          2,
          2,
          2,
          54,
          69,
          85,
          90,
          100,
          115,
          100,
          90,
          70,
          50,
          90,
          110,
          130,
          70,
          10,
        ],
        backgroundColor: "#db959a",
      },
      {
        label: "Zone 3",
        data: [
          163,
          114,
          101,
          95,
          86,
          70,
          65,
          60,
          54,
          54,
          17,
          15,
          38,
          10,
          10,
          20,
          55,
          70,
          100,
          70,
          30,
          20,
          40,
          90,
          120,
        ],
        backgroundColor: "#909e92",
      },
      {
        label: "Zone 4",
        data: [
          43,
          69,
          80,
          91,
          79,
          62,
          60,
          59,
          57,
          33,
          10,
          10,
          8,
          6,
          6,
          11,
          27,
          27,
          37,
          29,
          20,
          18,
          8,
          30,
          70,
        ],
        backgroundColor: "#739078",
      },
      {
        label: "Zone 5",
        data: [
          10,
          42,
          44,
          39,
          61,
          94,
          101,
          108,
          117,
          70,
          5,
          5,
          4,
          4,
          4,
          4,
          3,
          3,
          3,
          1,
          1,
          2,
          2,
          20,
          26,
        ],
        backgroundColor: "#5d7763",
      },
    ],
  };

  const options = {
    scales: {
      yAxes: [
        {
          stacked: true,
          ticks: {
            beginAtZero: true,
            count: 6,
            maxTicksLimit: 6,
            fontColor: "#5d7763",
            fontSize: 12,
            fontFamily: '"TT Hoves", sans-serif',
          },
          gridLines: {
            color: "rgba(255,255,255,0.1)",
            drawBorder: false,
            drawTicks: false,
          },
        },
      ],
      xAxes: [
        {
          stacked: true,
          ticks: {
            fontColor: "#5d7763",
            fontSize: 12,
            fontFamily: '"TT Hoves", sans-serif',
          },
        },
      ],
    },
    legend: {
      label: {
        color: "#5d7763",
        font: {
          size: 16,
          family: '"TT Hoves", sans-serif',
        },
      },
    },
    plugins: {
      datalabels: {
        display: false,
      },
    },
    tooltips: {
      mode: "index",
      intersect: false,
    },
    hover: {
      mode: "index",
      intersect: false,
    },
  };

  return (
    <>
      <Bar data={data} options={options} height={97.8}></Bar>
    </>
  );
}
